export enum RoutesApp {
  root = '',
  new = 'new',
  auth = 'auth',
  bull = 'toro',
  login = 'login',
  bulls = 'bulls',
  admin = 'admin',
  orders = 'orders',
  breeds = 'breeds',
  detail = 'detail',
  catalog = 'catalogo',
  checkout = 'comprar',
  register = 'register',
  settings = 'settings',
  dashboard = 'dashboard',
}
